## Neden NumPy?

- Numpy listelere göre çok daha hızlıdır. Çünkü sabit bir veri tipini tutar. (Listelerde birden fazla veri türü olabiliyordu)

- Listeler tek boyutlu Numpy arraylerine benzerler, Numpy'da tek indeksli diziler aynı şekilde **vektörler**, iki ya da daha fazla indeksli diziler ise **matrisler** ya da **tablolar** olarak adlandırılırlar.

- NumPy = Mumeric Python

In [7]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([3,5,6,8])
ab = a*b

In [21]:
#Dizimizi görelim
ab

array([ 3, 10, 18, 32])

In [22]:
#Dizimizin veri türü
type(ab)

numpy.ndarray

In [15]:
#Şimdi de istediğimiz sayıda integer türde 0'lardan oluşan bir numpy dizisi oluşturalım
np.zeros(7, dtype=int)

array([0, 0, 0, 0, 0, 0, 0])

In [18]:
#Belirttiğimiz aralıkta istediğimiz sayıda rasgele tam sayılar oluşturalım
np.random.randint(0, 70, size=10)

array([47,  8, 22, 31, 45, 19,  9, 52, 42, 44])

In [20]:
#Verdiğimiz değerlere göre rasgele bir dağılım oluşturalım
#np.random.normal(ortalama, standart sapma, boyut)
np.random.normal(10, 4, (3,4))

array([[10.69704234, 10.10708001,  9.73480669,  5.57332425],
       [-0.17964732,  7.90209379,  6.65356855,  5.76901168],
       [ 6.44004811,  7.48602313, 11.71265991, 11.81286783]])

## NumPy Array Özellikleri

In [2]:
import numpy as np

# [0, 10) aralığında 7 adet rasgele tamsayı üretip a dizisine atayalım
a = np.random.randint(10, size=7)
a

array([2, 5, 6, 8, 6, 1, 5])

Şimdi elde ettiğimiz bu dizinin özelliklerine göz atalım.

### Boyut Sayısı (ndim)

In [6]:
a.ndim

1

### Boyut Bilgisi (shape)

In [7]:
a.shape

(7,)

### Toplam Eleman Sayısı (size)

In [9]:
a.size

7

### Array Veri Tipi (dtype)

In [3]:
#Dizi elemanlarının veri türü
a.dtype

dtype('int32')

## Yeniden Şekillendirme (Reshaping)

In [11]:
import numpy as np

#İlk önce tek boyutlu bir dizi oluşturalım
arr = np.random.randint(1, 10, size=9)
arr

array([7, 8, 3, 4, 7, 8, 8, 4, 4])

In [13]:
#Şimdi de bunu 3x3'lük 2D bir diziye dönüştürelim
#reshape(self, shape, order)
arr.reshape(3, 3)

array([[7, 8, 3],
       [4, 7, 8],
       [8, 4, 4]])

## Index işlemleri

### 1) Tek Boyutlu Dizilerde Index İşlemleri

Önemli bir konudur. Bazı veri yapıları ile çalışırken bu yapılar içerisindeki verilere erişmek için kullandığımız yöntemlerdir. Bir örnekle pekiştirelim.

In [14]:
import numpy as np

myArr = np.random.randint(10, size=7)
myArr

array([3, 6, 1, 5, 3, 9, 1])

In [16]:
#Dizideki ilk elemana ulaşmak için,
myArr[0]

3

In [18]:
#İlk dört elemanı slice yöntemi ile alalım (ilk index dahil, sonuncu hariç)
myArr[:4]

array([3, 6, 1, 5])

In [19]:
#Son elemanı değiştirelim
myArr[-1] = 42
myArr

array([ 3,  6,  1,  5,  3,  9, 42])

### 2) İki Boyutlu Dizilerde İndex İşlemleri

In [21]:
#2D bir array oluşturalım; [0, 10) aralığında, boyutu 3x5 olan bir dizi (3 satır, 5 sütun)
m = np.random.randint(10, size=(3, 5))
m

array([[9, 2, 1, 2, 4],
       [9, 5, 6, 0, 6],
       [4, 4, 9, 0, 3]])

In [22]:
#2. satırda baştan 3. elemana ulaşalım
m[1][2]

6

In [23]:
#Bunu şu şekilde de yapabiliriz,
m[1,2]

6

In [25]:
#Şimdi de matristeki bir değeri değiştirelim
m[2,3] = 99
m

array([[ 9,  2,  1,  2,  4],
       [ 9,  5,  6,  0,  6],
       [ 4,  4,  9, 99,  3]])

**NOT:** NumPy dizileri tek tip veri saklar. Şayet bir NumPy dizisine farklı türde bir değer eklemek istersek bu değer dizinin veri türüne dönüştürülmeye çalışılır.

In [26]:
#Örnek: Az önce oluşturduğumuz tam sayı dizisine float bir değer eklemeye çalışalım
m[0,1] = 8.45
m

array([[ 9,  8,  1,  2,  4],
       [ 9,  5,  6,  0,  6],
       [ 4,  4,  9, 99,  3]])

Görüldüğü gibi değer int'e çevrilerek diziye eklendi.

**Matriste istediğimiz satır veya sütunları seçebiliriz.**

In [29]:
#Tüm satırların ilk sütununu seçelim
m[:, 0]

array([9, 9, 4])

In [30]:
#İkinci satırın tüm sütunlarını seçelim
m[1, :]

array([9, 5, 6, 0, 6])

**veya slicing ile daha spesifik bir alanı da seçebiliriz.** 

In [31]:
#Hatırlatma: İlk index dahil, sonuncu hariç
m[0:2, 1:4]

array([[8, 1, 2],
       [5, 6, 0]])

## Fancy Index

Elimizdeki bir dizinin belirli bir indeksindeki elemanlara nasıl ulaşacağımızı biliyoruz. Ulaşmak istediğimiz elemanlar birkaç taneden ibaretse herhangi bir sorun yaşamazken çok büyük dizilerde onlarca, yüzlerce elemana ulaşmamız gerekiyorsa eski yöntem baş ağrısına yol açacaktır.
NumPy bu sorun için de güzel bir çözüm sunmaktadır. İndeks değerlerini bir listeye atayıp tek bir komutla bu indekslerde bulunan tüm elemanlara ulaşmak. İşte karşınızda _fancy index_

In [32]:
import numpy as np

#arange(başlangıç değeri, bitiş değeri, adım sayısı) -> range metodu ile aynı parametrelere sahip
ciftSayilar = np.arange(0, 100, 3)
ciftSayilar

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [37]:
#İndeks değerlerine sahip listemizi oluşturalım
catch = [3, 7, 15, 22, 8]

In [40]:
#Şimdi de bu indekslerdeki elemanları alalım. Köşeli parantez kullandığımıza dikkat edin.
ciftSayilar[catch]

array([ 9, 21, 45, 66, 24])

## Koşullu İşlemler

Bazen bir veri setindeki belli bir koşula uyan değerleri çekmek isteyebiliriz. Bu işlemi NumPy çok kolaylaştırmıştır. Bir önceki konuda gördüğümüz _fancy index_ mantığını kullanarak ancak doğrudan index değerleri yazmak yerine koşul ifadesi yazabiliriz. Böylece o veri setinde belirttiğimiz koşula uyan değerlere ulaşırız.

In [44]:
import numpy as np

#Bir sayı dizisi oluşturalım
asal = np.array([2, 3, 5, 7])

In [46]:
#Bu dizideki her bir eleman için 3'ten büyük olma durumunu sorgulatalım
asal>3

array([False, False,  True,  True])

In [47]:
#Bu sorguyu fancy index şeklinde yazarsak bu sefer şarta uyan değerlere ulaşırız
asal[asal>3]

array([5, 7])

**NOT:** Şart ifadesi olarak herhangi bir koşul yazabiliriz.

## Matematiksel ve İstatistiksel İşlemler

NumPy ile bu işlemleri çok hızlı ve kolay bir şekilde yapabiliriz.

In [48]:
import numpy as np

sayilar = np.array([10,20,30,40,50])

In [50]:
#Tüm değerlere 5 ekleyelim
sayilar+5

array([15, 25, 35, 45, 55])

In [51]:
#Tüm değerlerden 3 çıkaralım
sayilar-3

array([ 7, 17, 27, 37, 47])

In [52]:
#Karelerini alalım
sayilar**2

array([ 100,  400,  900, 1600, 2500], dtype=int32)

**Metotları da işe koşabiliriz.**

In [53]:
#Toplama
np.add(sayilar, 3)

array([13, 23, 33, 43, 53])

In [54]:
#Çıkarma
np.subtract(sayilar, 5)

array([ 5, 15, 25, 35, 45])

In [55]:
#Ortalama
np.mean(sayilar)

30.0

In [56]:
#Elemanların toplamı
np.sum(sayilar)

150

In [57]:
#Mininmum değer
np.min(sayilar)

10

In [58]:
#Maksimum değer
np.max(sayilar)

50

In [59]:
#Varyans
np.var(sayilar)

200.0

Bunların dışında türev - integral alma, iki bilinmeyenli denklem çözme gibi işlemleri de yapabiliriz.